// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0K7-Op-9lUYZMH-WNcN-XnROwXyvM8is',
    appId: '1:683435240802:web:8b10109a6df9326aa9103b',
    messagingSenderId: '683435240802',
    projectId: 'mynotes-538c8',
    authDomain: 'mynotes-538c8.firebaseapp.com',
    storageBucket: 'mynotes-538c8.appspot.com',
    measurementId: 'G-FTB39S83VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkzYfP5bWJ2HZAnQ99uGb9enBLIuyVpZg',
    appId: '1:683435240802:android:41711ad73ac13078a9103b',
    messagingSenderId: '683435240802',
    projectId: 'mynotes-538c8',
    storageBucket: 'mynotes-538c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHNV9rOZyIu_WXaeyp1p3zCv3X0nMOHzU',
    appId: '1:683435240802:ios:cfab9c3aadd9eaa6a9103b',
    messagingSenderId: '683435240802',
    projectId: 'mynotes-538c8',
    storageBucket: 'mynotes-538c8.appspot.com',
    iosClientId: '683435240802-nd54p7mf2ir3s3ud60d2i1ceba619o7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHNV9rOZyIu_WXaeyp1p3zCv3X0nMOHzU',
    appId: '1:683435240802:ios:d07f477b8dd28e0ea9103b',
    messagingSenderId: '683435240802',
    projectId: 'mynotes-538c8',
    storageBucket: 'mynotes-538c8.appspot.com',
    iosClientId: '683435240802-jqrgentpn8q136rlqh7jppioamodgita.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
